import prisma from '../client';

const sampleRecipes = [
  // BREAKFAST RECIPES
  {
    name: 'Classic Scrambled Eggs',
    description: 'Fluffy scrambled eggs with butter and milk',
    category: 'BREAKFAST',
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    difficulty: 'EASY',
    calories: 180,
    protein: 14,
    carbs: 2,
    fats: 12,
    fiber: 0,
    sugar: 1,
    isVegetarian: true,
    isGlutenFree: true,
    ingredients: [
      { name: 'eggs', amount: 2, unit: 'large' },
      { name: 'butter', amount: 1, unit: 'tbsp' },
      { name: 'milk', amount: 2, unit: 'tbsp' },
      { name: 'salt', amount: 0.25, unit: 'tsp' },
      { name: 'pepper', amount: 0.125, unit: 'tsp' },
    ],
    instructions: [
      'Crack eggs into a bowl and whisk with milk, salt, and pepper',
      'Heat butter in a non-stick pan over medium heat',
      'Pour in eggs and gently stir with a spatula',
      'Cook until eggs are softly set and slightly runny in places',
      'Remove from heat and serve immediately',
    ],
  },
  {
    name: 'Overnight Oats',
    description: 'Easy make-ahead breakfast with oats, milk, and toppings',
    category: 'BREAKFAST',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'EASY',
    calories: 320,
    protein: 12,
    carbs: 52,
    fats: 8,
    fiber: 8,
    sugar: 12,
    isVegetarian: true,
    isPaleo: false,
    ingredients: [
      { name: 'rolled oats', amount: 0.5, unit: 'cup' },
      { name: 'milk', amount: 0.75, unit: 'cup' },
      { name: 'chia seeds', amount: 1, unit: 'tbsp' },
      { name: 'honey', amount: 1, unit: 'tbsp' },
      { name: 'banana', amount: 0.5, unit: 'medium' },
      { name: 'berries', amount: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Combine oats, milk, and chia seeds in a jar',
      'Stir in honey',
      'Cover and refrigerate overnight',
      'In the morning, top with sliced banana and berries',
      'Enjoy cold or heat in microwave for 1-2 minutes',
    ],
  },
  {
    name: 'Protein Pancakes',
    description: 'High-protein banana pancakes',
    category: 'BREAKFAST',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'EASY',
    calories: 250,
    protein: 20,
    carbs: 28,
    fats: 6,
    fiber: 3,
    sugar: 8,
    isVegetarian: true,
    isGlutenFree: true,
    ingredients: [
      { name: 'banana', amount: 1, unit: 'large' },
      { name: 'eggs', amount: 2, unit: 'large' },
      { name: 'protein powder', amount: 30, unit: 'g' },
      { name: 'baking powder', amount: 0.5, unit: 'tsp' },
      { name: 'cinnamon', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Mash banana in a bowl',
      'Whisk in eggs, protein powder, baking powder, and cinnamon',
      'Heat a non-stick pan over medium heat',
      'Pour batter to form 3-4 inch pancakes',
      'Cook for 2-3 minutes per side until golden',
      'Serve with fresh fruit',
    ],
  },

  // LUNCH RECIPES
  {
    name: 'Grilled Chicken Salad',
    description: 'Healthy grilled chicken with mixed greens',
    category: 'LUNCH',
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: 'EASY',
    calories: 350,
    protein: 35,
    carbs: 18,
    fats: 15,
    fiber: 6,
    sugar: 8,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      { name: 'chicken breast', amount: 150, unit: 'g' },
      { name: 'mixed greens', amount: 2, unit: 'cups' },
      { name: 'cherry tomatoes', amount: 0.5, unit: 'cup' },
      { name: 'cucumber', amount: 0.5, unit: 'medium' },
      { name: 'olive oil', amount: 1, unit: 'tbsp' },
      { name: 'lemon juice', amount: 1, unit: 'tbsp' },
      { name: 'salt', amount: 0.25, unit: 'tsp' },
      { name: 'pepper', amount: 0.125, unit: 'tsp' },
    ],
    instructions: [
      'Season chicken with salt and pepper',
      'Grill chicken for 6-7 minutes per side',
      'Let rest for 5 minutes, then slice',
      'Toss greens, tomatoes, and cucumber with olive oil and lemon',
      'Top with sliced chicken',
    ],
  },
  {
    name: 'Quinoa Buddha Bowl',
    description: 'Nutritious bowl with quinoa and vegetables',
    category: 'LUNCH',
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'MEDIUM',
    calories: 420,
    protein: 16,
    carbs: 58,
    fats: 14,
    fiber: 10,
    sugar: 6,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      { name: 'quinoa', amount: 1, unit: 'cup' },
      { name: 'chickpeas', amount: 1, unit: 'cup' },
      { name: 'sweet potato', amount: 1, unit: 'medium' },
      { name: 'kale', amount: 2, unit: 'cups' },
      { name: 'tahini', amount: 2, unit: 'tbsp' },
      { name: 'lemon juice', amount: 1, unit: 'tbsp' },
      { name: 'olive oil', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Roast diced sweet potato at 400°F for 20 minutes',
      'Massage kale with olive oil',
      'Arrange quinoa, chickpeas, sweet potato, and kale in bowl',
      'Drizzle with tahini mixed with lemon juice',
    ],
  },

  // DINNER RECIPES
  {
    name: 'Baked Salmon with Vegetables',
    description: 'Omega-3 rich salmon with roasted vegetables',
    category: 'DINNER',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: 'EASY',
    calories: 450,
    protein: 38,
    carbs: 22,
    fats: 24,
    fiber: 6,
    sugar: 8,
    isGlutenFree: true,
    isDairyFree: true,
    isPaleo: true,
    ingredients: [
      { name: 'salmon fillet', amount: 200, unit: 'g' },
      { name: 'broccoli', amount: 2, unit: 'cups' },
      { name: 'bell peppers', amount: 1, unit: 'medium' },
      { name: 'olive oil', amount: 2, unit: 'tbsp' },
      { name: 'lemon', amount: 0.5, unit: 'medium' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'herbs', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 400°F',
      'Place salmon and vegetables on baking sheet',
      'Drizzle with olive oil, season with garlic and herbs',
      'Bake for 15-20 minutes',
      'Squeeze fresh lemon over salmon before serving',
    ],
  },
  {
    name: 'Turkey Chili',
    description: 'Hearty and healthy turkey chili',
    category: 'DINNER',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'MEDIUM',
    calories: 380,
    protein: 32,
    carbs: 38,
    fats: 10,
    fiber: 12,
    sugar: 10,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      { name: 'ground turkey', amount: 500, unit: 'g' },
      { name: 'kidney beans', amount: 1, unit: 'can' },
      { name: 'diced tomatoes', amount: 1, unit: 'can' },
      { name: 'onion', amount: 1, unit: 'large' },
      { name: 'bell pepper', amount: 1, unit: 'medium' },
      { name: 'chili powder', amount: 2, unit: 'tbsp' },
      { name: 'cumin', amount: 1, unit: 'tsp' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
    ],
    instructions: [
      'Brown turkey in large pot',
      'Add diced onion, pepper, and garlic',
      'Stir in tomatoes, beans, and spices',
      'Simmer for 25-30 minutes',
      'Serve hot with toppings of choice',
    ],
  },
  {
    name: 'Chicken Stir-Fry',
    description: 'Quick and healthy Asian-inspired stir-fry',
    category: 'DINNER',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: 'EASY',
    calories: 420,
    protein: 36,
    carbs: 32,
    fats: 16,
    fiber: 5,
    sugar: 8,
    isDairyFree: true,
    ingredients: [
      { name: 'chicken breast', amount: 300, unit: 'g' },
      { name: 'mixed vegetables', amount: 3, unit: 'cups' },
      { name: 'soy sauce', amount: 2, unit: 'tbsp' },
      { name: 'ginger', amount: 1, unit: 'tbsp' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'sesame oil', amount: 1, unit: 'tbsp' },
      { name: 'rice', amount: 1, unit: 'cup' },
    ],
    instructions: [
      'Cook rice according to package',
      'Cut chicken into bite-sized pieces',
      'Heat sesame oil in wok or large pan',
      'Cook chicken until golden, about 5 minutes',
      'Add vegetables, ginger, and garlic',
      'Stir-fry for 3-4 minutes',
      'Add soy sauce and cook 1 more minute',
      'Serve over rice',
    ],
  },

  // SNACK RECIPES
  {
    name: 'Greek Yogurt Parfait',
    description: 'Protein-rich yogurt with fruit and granola',
    category: 'SNACK',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'EASY',
    calories: 220,
    protein: 18,
    carbs: 28,
    fats: 4,
    fiber: 4,
    sugar: 16,
    isVegetarian: true,
    isGlutenFree: false,
    ingredients: [
      { name: 'Greek yogurt', amount: 200, unit: 'g' },
      { name: 'mixed berries', amount: 0.5, unit: 'cup' },
      { name: 'granola', amount: 2, unit: 'tbsp' },
      { name: 'honey', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Layer yogurt in a glass or bowl',
      'Top with berries',
      'Sprinkle granola on top',
      'Drizzle with honey',
    ],
  },
  {
    name: 'Hummus with Veggies',
    description: 'Classic hummus with fresh vegetable sticks',
    category: 'SNACK',
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: 'EASY',
    calories: 180,
    protein: 8,
    carbs: 22,
    fats: 7,
    fiber: 8,
    sugar: 6,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      { name: 'hummus', amount: 0.5, unit: 'cup' },
      { name: 'carrots', amount: 1, unit: 'large' },
      { name: 'celery', amount: 2, unit: 'stalks' },
      { name: 'cucumber', amount: 0.5, unit: 'medium' },
      { name: 'bell pepper', amount: 0.5, unit: 'medium' },
    ],
    instructions: [
      'Cut all vegetables into sticks',
      'Arrange vegetables on a plate',
      'Serve with hummus for dipping',
    ],
  },

  // SMOOTHIE RECIPES
  {
    name: 'Green Protein Smoothie',
    description: 'Nutrient-packed green smoothie',
    category: 'SMOOTHIE',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'EASY',
    calories: 280,
    protein: 25,
    carbs: 38,
    fats: 5,
    fiber: 8,
    sugar: 22,
    isVegetarian: true,
    isGlutenFree: true,
    ingredients: [
      { name: 'spinach', amount: 2, unit: 'cups' },
      { name: 'banana', amount: 1, unit: 'medium' },
      { name: 'protein powder', amount: 30, unit: 'g' },
      { name: 'almond milk', amount: 1, unit: 'cup' },
      { name: 'peanut butter', amount: 1, unit: 'tbsp' },
      { name: 'ice', amount: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Add all ingredients to blender',
      'Blend on high until smooth',
      'Add more liquid if too thick',
      'Pour into glass and enjoy immediately',
    ],
  },
  {
    name: 'Berry Blast Smoothie',
    description: 'Antioxidant-rich berry smoothie',
    category: 'SMOOTHIE',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'EASY',
    calories: 240,
    protein: 12,
    carbs: 42,
    fats: 4,
    fiber: 8,
    sugar: 28,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      { name: 'mixed berries', amount: 1.5, unit: 'cups' },
      { name: 'banana', amount: 0.5, unit: 'medium' },
      { name: 'almond milk', amount: 1, unit: 'cup' },
      { name: 'chia seeds', amount: 1, unit: 'tbsp' },
      { name: 'vanilla extract', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Combine all ingredients in blender',
      'Blend until smooth and creamy',
      'Adjust thickness with more milk if needed',
      'Serve immediately',
    ],
  },
];

export async function seedRecipes() {
  console.log('Starting recipe seeding...');

  for (const recipeData of sampleRecipes) {
    try {
      await prisma.recipe.create({
        data: {
          name: recipeData.name,
          description: recipeData.description,
          category: recipeData.category as any,
          prepTime: recipeData.prepTime,
          cookTime: recipeData.cookTime,
          servings: recipeData.servings,
          difficulty: recipeData.difficulty as any,
          calories: recipeData.calories,
          protein: recipeData.protein,
          carbs: recipeData.carbs,
          fats: recipeData.fats,
          fiber: recipeData.fiber,
          sugar: recipeData.sugar,
          isVegetarian: recipeData.isVegetarian || false,
          isVegan: recipeData.isVegan || false,
          isGlutenFree: recipeData.isGlutenFree || false,
          isDairyFree: recipeData.isDairyFree || false,
          isKeto: recipeData.isKeto || false,
          isPaleo: recipeData.isPaleo || false,
          instructions: recipeData.instructions,
          ingredients: {
            create: recipeData.ingredients,
          },
        },
      });
      console.log(`✓ Created recipe: ${recipeData.name}`);
    } catch (error) {
      console.error(`✗ Failed to create recipe: ${recipeData.name}`, error);
    }
  }

  console.log(`Recipe seeding completed! Created ${sampleRecipes.length} recipes.`);
}

// Run if executed directly
if (require.main === module) {
  seedRecipes()
    .then(() => {
      console.log('Seeding finished');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seeding failed:', error);
      process.exit(1);
    });
}
